#!/usr/bin/env bash
# Deregisters an A2A agent from Gemini Enterprise.
# Generated by Terraform templatefile — do not edit manually.

set -euo pipefail

gcp_project="${gcp_project}"
gemini_enterprise_location="${gemini_enterprise_location}"

if [[ "$gemini_enterprise_location" == "global" ]]; then
  api_endpoint="discoveryengine.googleapis.com"
else
  api_endpoint="$${gemini_enterprise_location}-discoveryengine.googleapis.com"
fi

gemini_enterprise_agent_name="${gemini_enterprise_agent_name}"
collection_id="${collection_id}"
gemini_enterprise_app_id="${gemini_enterprise_app_id}"

# List agents to find ours by display name
echo -n "Fetching Gemini Enterprise agents by display name \"$${gemini_enterprise_agent_name}\": "
all_agents_output=$(curl -s -X GET \
    -H "Authorization: Bearer $(gcloud auth print-access-token)" \
    -H "x-goog-user-project: $(gcloud config get-value project 2>&1 | grep -v 'active config')" \
    -H "content-type: application/json" \
    "https://$${api_endpoint}/v1alpha/projects/$${gcp_project}/locations/$${gemini_enterprise_location}/collections/$${collection_id}/engines/$${gemini_enterprise_app_id}/assistants/default_assistant/agents")

all_agents_error=$(echo "$${all_agents_output}" | jq '.error')
if [[ "$${all_agents_error}" == "null" ]]; then
  echo "Success"
else
  echo "Failure: '$${all_agents_output}'"
  exit 1
fi

# Find agent by display name
agent_resource_name=""
if [[ "$${all_agents_output}" != "{}" ]]; then
  agent_resource_name=$(echo "$${all_agents_output}" | jq -r ".agents[]? | select(.displayName == \"$${gemini_enterprise_agent_name}\") | .name // empty")
fi

if [ -z "$${agent_resource_name}" ]; then
  echo "Gemini Enterprise agent not found with name \"$${gemini_enterprise_agent_name}\". Nothing to delete."
  exit 0
fi

# Delete the agent
echo -n "Deleting Gemini Enterprise agent \"$${agent_resource_name}\": "
delete_output=$(curl -s -X DELETE \
    -H "Authorization: Bearer $(gcloud auth print-access-token)" \
    -H "x-goog-user-project: $(gcloud config get-value project 2>&1 | grep -v 'active config')" \
    -H "content-type: application/json" \
    "https://$${api_endpoint}/v1alpha/$${agent_resource_name}")

delete_error=$(echo "$${delete_output}" | jq '.error')
if [[ "$${delete_error}" == "null" ]]; then
  echo "Success"
else
  echo "Failure: '$${delete_output}'"
  exit 1
fi

echo "$${delete_output}"
exit 0
