#!/usr/bin/env bash
# Registers or updates an A2A agent (Cloud Run) with Gemini Enterprise.
# Generated by Terraform templatefile — do not edit manually.

set -euo pipefail

gcp_project="${gcp_project}"
gemini_enterprise_location="${gemini_enterprise_location}"

if [[ "$gemini_enterprise_location" == "global" ]]; then
  api_endpoint="discoveryengine.googleapis.com"
else
  api_endpoint="$${gemini_enterprise_location}-discoveryengine.googleapis.com"
fi

gemini_enterprise_agent_name="${gemini_enterprise_agent_name}"
agent_description="${agent_description}"
collection_id="${collection_id}"
gemini_enterprise_app_id="${gemini_enterprise_app_id}"

# The agent card JSON is embedded at template render time
agent_card_json='${agent_card_json}'

# Compact + JSON-escape the card for embedding as a string value in the request body
agent_card_escaped=$(echo "$${agent_card_json}" | jq -c '.' | python3 -c "import sys, json; print(json.dumps(sys.stdin.read().strip()))")

# List existing agents to check if ours is already registered
echo -n "Fetching Gemini Enterprise agents by display name \"$${gemini_enterprise_agent_name}\": "
all_agents_output=$(curl -s -X GET \
    -H "Authorization: Bearer $(gcloud auth print-access-token)" \
    -H "x-goog-user-project: $(gcloud config get-value project 2>&1 | grep -v 'active config')" \
    -H "content-type: application/json" \
    "https://$${api_endpoint}/v1alpha/projects/$${gcp_project}/locations/$${gemini_enterprise_location}/collections/$${collection_id}/engines/$${gemini_enterprise_app_id}/assistants/default_assistant/agents")

all_agents_error=$(echo "$${all_agents_output}" | jq '.error')
if [[ "$${all_agents_error}" == "null" ]]; then
  echo "Success"
else
  echo "Failure: '$${all_agents_output}'"
  exit 1
fi

# Find existing agent by display name
existing_agent_resource_name=""
if [[ "$${all_agents_output}" != "{}" ]]; then
  existing_agent_resource_name=$(echo "$${all_agents_output}" | jq -r ".agents[]? | select(.displayName == \"$${gemini_enterprise_agent_name}\") | .name // empty")
fi

REQUEST_BODY=$(cat <<EOF
{
  "displayName": "$${gemini_enterprise_agent_name}",
  "description": "$${agent_description}",
  "a2aAgentDefinition": {
    "jsonAgentCard": $${agent_card_escaped}
  }
}
EOF
)

if [ -z "$${existing_agent_resource_name}" ]; then
  # Register new agent
  echo -n "Registering A2A agent \"$${gemini_enterprise_agent_name}\" with Gemini Enterprise app \"$${gemini_enterprise_app_id}\": "
  register_output=$(curl -s -X POST \
      -H "Authorization: Bearer $(gcloud auth print-access-token)" \
      -H "x-goog-user-project: $(gcloud config get-value project 2>&1 | grep -v 'active config')" \
      -H "content-type: application/json" \
      "https://$${api_endpoint}/v1alpha/projects/$${gcp_project}/locations/$${gemini_enterprise_location}/collections/$${collection_id}/engines/$${gemini_enterprise_app_id}/assistants/default_assistant/agents" \
      -d "$${REQUEST_BODY}")

  register_error=$(echo "$${register_output}" | jq '.error')
  if [[ "$${register_error}" == "null" ]]; then
    echo "Success"
  else
    echo "Failure: '$${register_output}'"
    exit 1
  fi

  echo "$${register_output}"
  exit 0
fi

# Update existing agent
echo -n "Updating A2A agent \"$${gemini_enterprise_agent_name}\" on Gemini Enterprise app \"$${gemini_enterprise_app_id}\": "
patch_output=$(curl -s -X PATCH \
    -H "Authorization: Bearer $(gcloud auth print-access-token)" \
    -H "x-goog-user-project: $(gcloud config get-value project 2>&1 | grep -v 'active config')" \
    -H "content-type: application/json" \
    "https://$${api_endpoint}/v1alpha/$${existing_agent_resource_name}" \
    -d "$${REQUEST_BODY}")

patch_error=$(echo "$${patch_output}" | jq '.error')
if [[ "$${patch_error}" == "null" ]]; then
  echo "Success"
else
  echo "Failure: '$${patch_output}'"
  exit 1
fi

echo "$${patch_output}"
exit 0
