# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:

  - name: "gcr.io/cloud-builders/gcloud-slim"
    id: trigger-deployment
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "agent-a2ui-skill-demo"
      - "--image"
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME"
      - "--region"
      - "$_REGION"
      - "--project"
      - $_PROD_PROJECT_ID
      - "--service-account"
      - "$_APP_SERVICE_ACCOUNT_PROD"
      - "--no-allow-unauthenticated"
      - "--update-env-vars"
      - "GOOGLE_CLOUD_PROJECT=${_PROD_PROJECT_ID},GOOGLE_CLOUD_LOCATION=global,GOOGLE_GENAI_USE_VERTEXAI=true,WORKSPACE_USER_EMAIL=${_WORKSPACE_USER_EMAIL}"


substitutions:
  _PROD_PROJECT_ID: YOUR_PROD_PROJECT_ID
  _REGION: us-central1
  _CONTAINER_NAME: agent-a2ui-skill-demo
  _ARTIFACT_REGISTRY_REPO_NAME: agent-a2ui-skill-demo
  _APP_SERVICE_ACCOUNT_PROD: agent-a2ui-skill-demo-sa@YOUR_PROD_PROJECT_ID.iam.gserviceaccount.com # pragma: allowlist secret
  _WORKSPACE_USER_EMAIL: ''


logsBucket: gs://${PROJECT_ID}-agent-a2ui-skill-demo-logs/build-logs
options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
